# Generated by Django 2.0.3 on 2018-04-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
